env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:n/recommended'
  - 'plugin:import/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: error
  prefer-const: error
  no-var: error
  n/exports-style: [0, error]
  import/first: error
  import/no-anonymous-default-export: error
  import/no-unassigned-import: error
  import/no-internal-modules:
    - error
    - allow:
        - '**/lib/*'
