#!/usr/bin/env node

const fs = require('fs');
const jsdoc2md = require('jsdoc-to-markdown');

let original = fs.readFileSync('./lib/index.js').toString();
const incompatibleJsdocTypings = original.match(/import\('(.*)'\)/gm);

let replaced = '';
let loops = incompatibleJsdocTypings.length;
function iterate() {
  const current = incompatibleJsdocTypings.shift();
  const dep = original.match(/import\('(.*)'\)/);
  
  if (dep && current) {
    replaced += original
      .slice(0, original.indexOf(current) + current.length)
      .replace(/import\('(.*)'\)/, dep[1])
    original = original.slice(original.indexOf(current) + current.length);
  } else {
    replaced += original;
  }

  if (loops--) iterate();
}
iterate()
fs.writeFileSync('./jsdoc2md-src.js', replaced);

jsdoc2md
  .render({
    files: './jsdoc2md-src.js',
    "no-gfm": true,
    "name-format": false
  })
  .then(mdContent => {
    require('fs').writeFileSync('jsdoc.md', mdContent)
  })